### ISSUE TITLE
Check out the A-frame inspector 

### ISSUE THREAD

**Issue by abdulsalam0** [abdulsalam0/CLEVR#8]
## Check out  this link to build an understanding of how it works
https://aframe.io/docs/1.0.0/introduction/visual-inspector-and-dev-tools.html

to run it use 
`<ctrl> + <alt> + i`

##github Link
https://github.com/aframevr/aframe-inspector

**Comment by Advaith98** [comment]
Messed around with the different concepts of A-frame inspector
